# Generated by Django 6.0.1 on 2026-02-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pendente_documentos', 'Pendente de Documentos'), ('documentos_ok', 'Documentos OK'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do atendimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('validacao_documento', 'Validação de Documento'), ('upload_documento', 'Upload de Documento'), ('reenvio_documento', 'Reenvio de Documento'), ('vinculo_cartorio', 'Vínculo de Cartório'), ('alteracao_role', 'Alteração de Papel'), ('criacao_usuario', 'Criação de Usuário'), ('criacao_agendamento', 'Criação de Agendamento'), ('edicao_agendamento', 'Edição de Agendamento'), ('cancelamento_agendamento', 'Cancelamento de Agendamento'), ('confirmacao_agendamento', 'Confirmação de Agendamento')], max_length=50)),
                ('descricao', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Cartorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('capacidade_diaria', models.PositiveIntegerField(default=0, help_text='Quantidade máxima de atendimentos por dia', verbose_name='Capacidade diária')),
                ('abertura', models.TimeField(blank=True, null=True, verbose_name='Horário de abertura')),
                ('fechamento', models.TimeField(blank=True, null=True, verbose_name='Horário de fechamento')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso'), ('arquivado', 'Arquivado')], default='ativo', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cartório',
                'verbose_name_plural': 'Cartórios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso'), ('arquivado', 'Arquivado')], default='ativo', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categorias de Documentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do documento')),
                ('arquivo', models.FileField(upload_to='agendamentos/documentos/', verbose_name='Arquivo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacao_validacao', models.TextField(blank=True, null=True, verbose_name='Observação da validação')),
                ('validado_em', models.DateTimeField(blank=True, null=True, verbose_name='Validado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('prazo_validacao_em', models.DateTimeField(blank=True, null=True, verbose_name='Prazo máximo para validação')),
                ('sla_estourado', models.BooleanField(default=False, verbose_name='SLA estourado')),
            ],
            options={
                'verbose_name': 'Documento do Agendamento',
                'verbose_name_plural': 'Documentos do Agendamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAgendamentoValidacaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=20, verbose_name='Status anterior')),
                ('status_novo', models.CharField(max_length=20, verbose_name='Status novo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação da validação')),
                ('validado_em', models.DateTimeField(auto_now_add=True, verbose_name='Validado em')),
            ],
            options={
                'verbose_name': 'Histórico de Validação de Documento',
                'verbose_name_plural': 'Históricos de Validação de Documento',
                'ordering': ['-validado_em'],
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('codigo_ibge', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código IBGE')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso'), ('arquivado', 'Arquivado')], default='ativo', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoCartorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso'), ('arquivado', 'Arquivado')], default='ativo', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Tipo de Cartório',
                'verbose_name_plural': 'Tipos de Cartório',
                'ordering': ['nome'],
            },
        ),
    ]
