# Generated by Django 6.0.1 on 2026-02-13 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_profissional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='app.agendamento', verbose_name='Agendamento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_profissional', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_representante', to=settings.AUTH_USER_MODEL, verbose_name='Representante'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario_afetado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario_executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_executadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartorio',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartorios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cartorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='app.cartorio', verbose_name='Cartório'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cartorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cartorio'),
        ),
        migrations.AddField(
            model_name='documentoagendamento',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.agendamento'),
        ),
        migrations.AddField(
            model_name='documentoagendamento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoriadocumento', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='documentoagendamento',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.AddField(
            model_name='documentoagendamentovalidacaohistorico',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_validacoes', to='app.documentoagendamento', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='documentoagendamentovalidacaohistorico',
            name='validado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validacoes_documentos', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.AddField(
            model_name='cartorio',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartorios', to='app.municipios', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='cartorio',
            name='tipo_cartorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartorios', to='app.tipocartorio', verbose_name='Tipo de Cartório'),
        ),
    ]
